-- AlterTable
ALTER TABLE "Ad" ALTER COLUMN "business_name" DROP NOT NULL,
ALTER COLUMN "destination_url" DROP NOT NULL,
ALTER COLUMN "Description" DROP NOT NULL,
ALTER COLUMN "Niches" DROP NOT NULL,
ALTER COLUMN "keywords" DROP NOT NULL,
ALTER COLUMN "wallet_address" DROP NOT NULL,
ALTER COLUMN "cost_per_click" DROP NOT NULL,
ALTER COLUMN "Weekly_Clicks" DROP NOT NULL,
ALTER COLUMN "Weekly_Cost" DROP NOT NULL;
